version: "3"
services:
  postgresdb:
    image: postgres:12.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hello_dev
    ports:
      - 5432:5432